- name: Directories are present
  file:
    path="{{ item }}"
    state=directory
    mode=777
  with_items: directories
  tags: [jenkins]

- name: Packages are present
  apt:
    name="{{ item }}"
    state=present
  with_items: packages
  tags: [jenkins]

- name: Container is running
  docker:
    name=jenkins
    image=vfarcic/jenkins
    ports=8080:8080
    volumes=/data/jenkins:/jenkins
  tags: [jenkins]