- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.10.5
    state: present
  tags: [docker]

- name: Files are present
  copy:
    src: docker
    dest: /etc/default/docker
  register: copy_result
  tags: [docker]

- name: Ensure docker-compose is installed and available
  shell: curl -L https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

- name: Ensure docker-compose has executable
  shell: chmod +x /usr/local/bin/docker-compose

- name: Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed
  tags: [docker]
